---
  extends:
    - "airbnb"
  parser: "babel-eslint"
  rules:
    no-underscore-dangle: 0
    import/no-unresolved: 0
    better/no-new: 0
    import/no-extraneous-dependencies: 0
    react/jsx-filename-extension: 0
    react/require-extension: 0
  env:
    browser: true
    mocha: true
    jasmine: true
  plugins:
    - "react"
    - "jsx-a11y"
  globals:
    __DEBUG__: true
    __DEV__: true
    sinon: true
